# Generated by Django 3.1.7 on 2021-03-26 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crypto_api', '0002_crypto_current_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simple_return', models.FloatField(null=True)),
                ('log_return', models.FloatField(null=True)),
                ('beta', models.FloatField(null=True)),
                ('crypto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crypto_api.crypto')),
            ],
        ),
    ]
