# Generated by Django 3.1.7 on 2021-03-28 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_api', '0002_auto_20210328_2033'),
        ('data_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='ticker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crypto_api.crypto'),
        ),
    ]
