# Generated by Django 3.1.7 on 2021-03-26 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_api', '0002_crypto_current_price'),
        ('data_analysis', '0002_auto_20210326_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='crypto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto_api.crypto'),
        ),
    ]
