# Generated by Django 3.1.7 on 2021-03-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=25, unique=True)),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
